name = "road-dj-api"
main = "backend-worker.js"
compatibility_date = "2026-09-01"
keep_vars = true

[vars]
FRONTEND_ORIGIN = "https://halowars.github.io"
SPOTIFY_CLIENT_ID = "00c2bd4d6a7e45efbc4a766bf80e54c7"

[[kv_namespaces]]
binding = "ROAD_DJ_AUTH"

[[durable_objects.bindings]]
name = "ROAD_DJ_LIVE"
class_name = "RoadDJLive"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoadDJLive"]
